import type { Metadata } from "next";
import Grid from '@mui/material/Grid2';
import "./globals.css";
import HeaderCard from "@/components/cards/headerCard";
import { Container, ThemeProvider } from "@mui/material";
import responsiveTheme from "@/components/ui/theme";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <ThemeProvider theme={responsiveTheme}>
          <Container maxWidth='lg'>
            <Grid container  spacing={2}>
              <Grid size={4} height='100vh'>
                <HeaderCard />
              </Grid>
              <Grid size={8}>
                {children}
              </Grid>
            </Grid>
          </Container>
        </ThemeProvider>
      </body>
    </html>
  );
}
